### PR TITLE
Single outfile

### PR DESCRIPTION
**Pull request by sanguinariojoe**
Cherry-picked from https://github.com/mattEhall/MoorDyn/pull/35

### CODE REVIEW

**Comment by sanguinariojoe** [comment]
@djanders19 , please, check this out... I did not even tested it

**Comment by sanguinariojoe** [comment]
I rebased this PR to v2

@djanders19 , did you test it?

**Comment by mattEhall** [comment]
@djanders19, @sanguinariojoe - am I right that this PR is where the nice option of a single output file lives, but it needs checking before being merged in?  

I've just merged in #51, where the many other PRs were nicely combined.

Are there any other outstanding items from #35 that we should think about, or was that all covered in #51?

**Comment by sanguinariojoe** [comment]
Yeah, this was not tested. That's why I excluded it from #51

AFAIK all changes on #35 are included in both this PR and #51

**Pull request closed without merging**
