### PR TITLE
Fixes for rods

### PR DESCRIPTION
**Pull request by sanguinariojoe**
Just to let you know that I am working on fixing rods, so @mattEhall do not waste your time on them

### CODE REVIEW

**Comment by sanguinariojoe** [comment]
Well, the rods seems to be working now. But there is an open question though...

Now the rods are featured, at least for the sake of integration, by the end point A and the orientation angles. However, the coupling is still done in terms of direction vector. That is obviously introducing errors of the order of the rotation velocity by the outer time step (the one used when you call `MoorDyn_Step()`)

I suppose the way to go is changing the rods coupling to work with the orientation angles as well, but any thought is welcomed @mattEhall and @djanders19

**Comment by sanguinariojoe** [comment]
"errors of the order of the rotation velocity":

Let's figure an horizontal rod, q = [1, 0, 0], rotating at a constant speed, w = [0, 0, pi]. Let's say the inner time step is dtM = 0.001 (it does not matter too much) and the outer time step is dt = 1.0 (the one we are passing to https://github.com/FloatingArrayDesign/MoorDyn/blob/v2/source/MoorDyn2.h#L191).

Then, x = q, and xd = [-2, 0, 0]. The q vector will become [1, 0, 0] for the first half of the outer time step, and [-1, 0, 0] for the second half.

That is a super-special case, of course. But in general the rotation will be represented with an error of order O(w * dt)

**Comment by mattEhall** [comment]
The case you described involves combines a rapid rotation with a very large coupling time step, such that something rotates 180 deg over a single coupling time step. I'd consider that just a bad setup, because the coupling time step should always be small enough so that the dynamics at the coupling point can be approximated as linear between time steps. I.e. I'd ensure the coupling time step is small enough to keep rotations to under 5 degrees per step. Otherwise there's no way it would be reliable dynamic coupling.

Is that the only issue?

**Comment by sanguinariojoe** [comment]
That's why I say the error is or order O(w * dt). If the outer step/coupling step by the rotation speed is small, the error will be small.

The point is the rods are internally handled by position and orientation angles now. Thus we can ask for angles instead of directions on the coupling, so there will be no error anymore. On the other hand, angles would be less intuitive.

So we just need to decide the way we want to go:

 - Receiving orientation angles (EulerXYZ) from the user
 - Changing the documentation to state that the outer time step should be small enough to grant small errors

**Comment by mattEhall** [comment]
I think we should keep the coupling as before, using direction vectors for the rods.

The outer time step should always be small enough to grant small errors, whether in rotation or translation!

**Comment by sanguinariojoe** [comment]
Ok! Then I am merging this!

**Pull request merged**
