### PR TITLE
Some minor changes to prepare for the 2.3.8 release

### PR DESCRIPTION
**Pull request by sanguinariojoe**
Just a couple of tweaks to launch the 2.3.8 release. Tomorrow I am still on the office. If we do not launch the missiles @RyanDavies19, we will have to wait until 12-dic (not really a drama anyway)

### CODE REVIEW

**Comment by RyanDavies19** [comment]
@sanguinariojoe this all looks good, could we change the filename to polyester.py to keep things consistent? 

Also just to confirm, this python test is the same as the cpp test right? When I merge in the viscoelastic capability should the tests be put in both of these or is just the cpp one sufficient?

**Comment by sanguinariojoe** [comment]
> @sanguinariojoe this all looks good, could we change the filename to polyester.py to keep things consistent?

I am afraid not. PyTest has the `test_*` naming policy (I suppose it can be done, but some hacking will be required that is probably backfiring on the future)

> Also just to confirm, this python test is the same as the cpp test right? When I merge in the viscoelastic capability should the tests be put in both of these or is just the cpp one sufficient?

cpp is surely enough

**Comment by RyanDavies19** [comment]
@sanguinariojoe was this intended to trigger a release? Trying to work through some bugs with the 2.3.7 windows DLL causing GH actions to crash on the WECSim tests. I notices though we don't have any PR documenting the 2.3.8 release but the binaries are available.

**Comment by sanguinariojoe** [comment]
Nope. It is because master and dev diverged, so I did the release forcily pushing on master. See https://github.com/FloatingArrayDesign/MoorDyn/issues/278

**Pull request merged**
