### PR TITLE
Rod Dynamics Updates

### PR DESCRIPTION
**Pull request by RyanDavies19**
Updates and improvements to rod dynamics. These changes reflect the rod dynamics in the OpenFAST version of MoorDyn, they have been verified against the MoorDynF code.

I'm still getting the hang of how to do pull requests, so let me know if something is wrong here.

### CODE REVIEW

**Comment by sanguinariojoe** [comment]
Hey Ryan! TY so much!

The biggest problem here is that you have not rebased, so there are many conflicts. Don't panic though! We are here to help each other!

I assume you already [set up the upstream](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-repository-for-a-fork). So the first step is always downloading the latest version here, on the upstream (this will modify nothing on your branches, so it is a safe operation):

`git fetch upstream`

You definitely want to preserve your changes somewhere, so nothing bad happens and you need to redo your job. So first thing to do is moving to a different branch:
`
git checkout -b v2_rods`

NOTE:  in general I recommend you to work on different branches, so you can keep your v2 synced with this, i.e. the upstream

Now, you are resetting your branch to a state before things started diverging (remember, all your changes and safe on your v2 branch, so do not worry):

`git reset --hard 97bfacbddcbb19d7cae21b1b7e898653c750dec2`

NOTE: You can use a graphical interface to check when things started diverging. I use gitg

Now you can sync with the upstream, so your v2_rods will be the same than the v2 here.

`git rebase upstream/v2`

Looking at this PR, it seems that the only changes you introduced are [on this comit](https://github.com/FloatingArrayDesign/MoorDyn/pull/89/commits/113163a3cb2f7f4f2cd44e6139111bb8eec8c159). Thus you can [cherry-pick](https://git-scm.com/docs/git-cherry-pick) it:

`git cherry-pick 113163a3cb2f7f4f2cd44e6139111bb8eec8c159`

NOTE: Maybe (or maybe not) you have a conflict when doing this because you have added the change on Wave.h of the last PR on this very same commit. Do not do that in the future. In any case I am sure you are not having major issues fixing it.

So you can push your changes:

`git push origin v2_rods`

And open a new Pull Request using this branch (against v2 too). After I will provide you with the commands to fix your v2 branch, and some hints so you avoid this happening to you again

**Comment by RyanDavies19** [comment]
Pepe, thanks for the tips on git. I will work on rebasing and cleaning up my branch today and get back to you. 

Alex, if a substantial PR is coming later today then I will wait for that and then manually copy over any additional changes. There aren't too many so it should be manageable. The new coefficients and buoyancy terms all come from the MoorDynF code, which I was verifying v2 against. I will chat with Matt about those adjustments today. Once your PR is up I will run some more comparisons with MoorDynF (though it seems like it needs some updates as well with regards to rotations).

**Comment by RyanDavies19** [comment]
Pepe, 

I went through and did the rebase on a new branch, v2_ryan. I am going to hold off on creating a PR until I get a get a chance to check out the new PR from Kelson

**Comment by sanguinariojoe** [comment]
Nice!

Can you please visit [the big PR from Kelson](https://github.com/FloatingArrayDesign/MoorDyn/pull/90) with @mattEhall ?

**Comment by RyanDavies19** [comment]
Closing this as updates will be coming in separate changes to code

**Pull request closed without merging**
